logging:
  file:
    name: log/microservice.chassis.log
  pattern:
    dateformat: "HH:mm:ss.SSS"

spring:
  devtools:
    restart:
      additional-paths:
        - conf/**
  main:
    banner-mode: 'off'

server:
  port: 8004

